USE FurnitureFirm

--Countries TABLE
INSERT INTO Countries(Name) VALUES('Україна')
INSERT INTO Countries(Name) VALUES('Польща')
INSERT INTO Countries(Name) VALUES('Німеччина')
INSERT INTO Countries(Name) VALUES('Росія')
INSERT INTO Countries(Name) VALUES('США')
INSERT INTO Countries(Name) VALUES('Китай')
INSERT INTO Countries(Name) VALUES('Японія')
INSERT INTO Countries(Name) VALUES('Фінляднія')
INSERT INTO Countries(Name) VALUES('Франція')
INSERT INTO Countries(Name) VALUES('Італія')
INSERT INTO Countries(Name) VALUES('Іспанія')

--Cities TABLE
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Київ')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Львів')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Чернівці')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Рівне')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Сокаль')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Тернопіль')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Черкаси')
INSERT INTO Cities(CountryId, Name) VALUES(1, 'Херсон')

--Colors TABLE
INSERT INTO Colors(Name) VALUES('Синій')
INSERT INTO Colors(Name) VALUES('Зелений')
INSERT INTO Colors(Name) VALUES('Жовтий')
INSERT INTO Colors(Name) VALUES('Червоний')
INSERT INTO Colors(Name) VALUES('Чорний')
INSERT INTO Colors(Name) VALUES('Білий')
INSERT INTO Colors(Name) VALUES('Сірий')
INSERT INTO Colors(Name) VALUES('Коричновий')

--Materials TABLE
INSERT INTO Materials(Name) VALUES('Дерево')
INSERT INTO Materials(Name) VALUES('ДСП')
INSERT INTO Materials(Name) VALUES('Фанера')
INSERT INTO Materials(Name) VALUES('Скло')
INSERT INTO Materials(Name) VALUES('Акрил')
INSERT INTO Materials(Name) VALUES('Сталь')
INSERT INTO Materials(Name) VALUES('Пластик')

--Producers TABLE
INSERT INTO Producers(Name, CountryId) VALUES('Materials Inc', 5)
INSERT INTO Producers(Name, CountryId) VALUES('BestMat', 1)
INSERT INTO Producers(Name, CountryId) VALUES('Mat4U', 9)
INSERT INTO Producers(Name, CountryId) VALUES('MatProd', 1)

--Providers TABLE
INSERT INTO Providers(Name, CityId, PhoneNumber, Street, Building) VALUES('Fast&Furious', 8, '+380515767', 'Шевченка', 24)
INSERT INTO Providers(Name, CityId, PhoneNumber, Street, Building) VALUES('BestProv', 6, '+380264386', 'Головна', 27)
INSERT INTO Providers(Name, CityId, PhoneNumber, Street, Building) VALUES('Provide4You', 8, '+380209563', 'Дорошенка', 15)
INSERT INTO Providers(Name, CityId, PhoneNumber, Street, Building) VALUES('DetProv Inc', 3, '+380633023', 'Комарова', 4)

--Details TABLE
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 7, 3, 'Деталь 1', 828)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 1, 4, 'Деталь 2', 433)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 5, 2, 'Деталь 3', 675)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 7, 4, 'Деталь 4', 165)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 8, 2, 'Деталь 5', 957)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 6, 2, 'Деталь 6', 894)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 7, 4, 'Деталь 7', 323)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 6, 3, 'Деталь 8', 113)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 6, 4, 'Деталь 9', 151)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(4, 2, 2, 'Деталь 10', 696)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 1, 1, 'Деталь 11', 334)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 5, 4, 'Деталь 12', 948)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 3, 3, 'Деталь 13', 277)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 5, 2, 'Деталь 14', 585)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 3, 4, 'Деталь 15', 424)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 4, 4, 'Деталь 16', 544)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 2, 2, 'Деталь 17', 442)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 7, 4, 'Деталь 18', 604)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 4, 4, 'Деталь 19', 440)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 5, 4, 'Деталь 20', 248)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 6, 2, 'Деталь 21', 456)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 1, 1, 'Деталь 22', 811)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 5, 3, 'Деталь 23', 340)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 2, 2, 'Деталь 24', 249)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 7, 3, 'Деталь 25', 642)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 1, 4, 'Деталь 26', 555)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(4, 8, 2, 'Деталь 27', 313)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 4, 2, 'Деталь 28', 980)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(4, 3, 1, 'Деталь 29', 819)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 7, 1, 'Деталь 30', 148)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 6, 3, 'Деталь 31', 764)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(4, 5, 1, 'Деталь 32', 950)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 5, 1, 'Деталь 33', 177)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 7, 2, 'Деталь 34', 457)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(4, 3, 3, 'Деталь 35', 695)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 3, 4, 'Деталь 36', 826)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 6, 3, 'Деталь 37', 956)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 4, 3, 'Деталь 38', 192)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 5, 3, 'Деталь 39', 122)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 5, 2, 'Деталь 40', 581)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 2, 4, 'Деталь 41', 440)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 6, 1, 'Деталь 42', 543)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 8, 4, 'Деталь 43', 398)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 5, 2, 'Деталь 44', 199)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 8, 4, 'Деталь 45', 883)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 8, 3, 'Деталь 46', 117)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 8, 4, 'Деталь 47', 594)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 5, 2, 'Деталь 48', 555)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 1, 1, 'Деталь 49', 503)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 1, 1, 'Деталь 50', 862)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 3, 4, 'Деталь 51', 446)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(3, 7, 2, 'Деталь 52', 762)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(2, 4, 3, 'Деталь 53', 320)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(1, 4, 2, 'Деталь 54', 517)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 3, 1, 'Деталь 55', 439)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 5, 3, 'Деталь 56', 906)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(7, 3, 3, 'Деталь 57', 952)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(6, 2, 2, 'Деталь 58', 700)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(5, 3, 4, 'Деталь 59', 305)
INSERT INTO Details(MaterialId, ColorId, ProducerId, Name, Price) VALUES(4, 3, 2, 'Деталь 60', 481)

--Warehouses TABLE
INSERT INTO Warehouses(CityId, Street, Building) VALUES(5, 'Дорошенка', 25)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(7, 'Комарова', 20)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(7, 'Бандери', 28)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(3, 'Київська', 26)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(7, 'Свободи', 8)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(8, 'Бандери', 9)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(8, 'Комарова', 1)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(3, 'Бандери', 23)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(6, 'Шевченка', 29)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(2, 'Бандери', 9)
INSERT INTO Warehouses(CityId, Street, Building) VALUES(8, 'Київська', 14)

--WarehouseDetails TABLE
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(32, 11, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(46, 11, 1)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(9, 1, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(41, 2, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(54, 8, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(26, 15, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(26, 16, 2)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(59, 18, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(23, 15, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(39, 4, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(18, 7, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(55, 4, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(1, 17, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(22, 1, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(26, 11, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(52, 1, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(52, 12, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(25, 16, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(17, 6, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(57, 3, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(59, 3, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(11, 4, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(19, 19, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(27, 3, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(46, 18, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(6, 4, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(2, 5, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(23, 6, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(11, 9, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(6, 8, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(8, 16, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(14, 12, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(57, 20, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(4, 13, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(11, 10, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(6, 6, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(35, 10, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(14, 5, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(42, 11, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(50, 20, 1)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(47, 3, 1)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(5, 10, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(35, 9, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(49, 11, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(26, 9, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(22, 4, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(25, 12, 2)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(50, 1, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(24, 3, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(36, 13, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(49, 7, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(52, 17, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(57, 2, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(59, 13, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(18, 10, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(4, 10, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(12, 2, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(30, 13, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(5, 18, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(40, 18, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(55, 4, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(57, 8, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(52, 20, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(19, 13, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(47, 20, 1)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(38, 5, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(39, 1, 6)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(25, 1, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(28, 4, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(13, 12, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(16, 3, 2)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(22, 4, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(5, 4, 1)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(22, 3, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(15, 14, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(59, 13, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(16, 10, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(5, 12, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(46, 8, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(28, 18, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(55, 5, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(12, 6, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(49, 16, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(44, 7, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(18, 7, 3)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(13, 18, 2)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(52, 4, 2)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(12, 2, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(6, 16, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(56, 18, 2)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(40, 10, 1)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(3, 17, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(23, 15, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(29, 12, 9)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(54, 17, 5)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(5, 17, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(30, 4, 7)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(43, 14, 10)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(59, 14, 8)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(30, 16, 4)
INSERT INTO WarehouseDetails(DetailId, Count, WarehouseId) VALUES(10, 18, 7)

--Categories TABLE
INSERT INTO Categories(Name) VALUES('Робочі Столи')
INSERT INTO Categories(Name) VALUES('Шафи')
INSERT INTO Categories(Name) VALUES('Ліжка')
INSERT INTO Categories(Name) VALUES('Дзеркала')
INSERT INTO Categories(Name) VALUES('Стільчики')
INSERT INTO Categories(Name) VALUES('Обідні Столи')
INSERT INTO Categories(Name) VALUES('Дивани')
INSERT INTO Categories(Name) VALUES('Стелажі')

--Styles TABLE
INSERT INTO Styles(Name) VALUES('Традиційний')
INSERT INTO Styles(Name) VALUES('Модерн')
INSERT INTO Styles(Name) VALUES('Сучасний')
INSERT INTO Styles(Name) VALUES('Перехідний')
INSERT INTO Styles(Name) VALUES('Преміум')

--Collections TABLE
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  1', 3)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  2', 2)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  3', 4)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  4', 1)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  5', 3)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  6', 5)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  7', 1)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  8', 5)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  9', 2)
INSERT INTO Collections(Name, StyleId) VALUES('COLLECTION  10', 3)

--Furnitures TABLE
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  1', 4, 4, 670, 307, 861, 5, 311)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  2', 9, 6, 422, 549, 924, 10, 697)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  3', 9, 2, 314, 817, 162, 5, 445)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  4', 5, 8, 663, 663, 116, 1, 536)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  5', 10, 8, 936, 218, 544, 2, 469)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  6', 4, 2, 956, 889, 569, 8, 699)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  7', 1, 3, 133, 428, 250, 3, 617)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  8', 10, 8, 250, 764, 230, 8, 472)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  9', 4, 1, 964, 801, 181, 7, 640)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  10', 7, 8, 938, 885, 377, 3, 477)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  11', 9, 2, 379, 649, 300, 6, 752)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  12', 9, 5, 577, 359, 126, 7, 806)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  13', 4, 4, 713, 262, 834, 10, 770)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  14', 10, 2, 163, 980, 899, 7, 338)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  15', 7, 7, 290, 714, 837, 5, 828)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  16', 3, 4, 411, 374, 974, 7, 614)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  17', 9, 3, 304, 520, 952, 9, 355)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  18', 6, 1, 578, 554, 454, 8, 713)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  19', 4, 1, 166, 749, 982, 10, 990)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  20', 8, 1, 652, 320, 963, 6, 869)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  21', 10, 5, 760, 811, 583, 1, 365)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  22', 7, 3, 789, 977, 903, 3, 128)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  23', 10, 1, 806, 748, 265, 10, 400)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  24', 7, 3, 299, 820, 616, 10, 901)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  25', 3, 2, 629, 655, 358, 9, 463)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  26', 1, 5, 165, 113, 956, 1, 309)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  27', 9, 6, 915, 268, 149, 1, 784)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  28', 2, 2, 446, 742, 926, 6, 864)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  29', 1, 6, 741, 179, 884, 5, 480)
INSERT INTO Furnitures(Name, TimeToBuild, CategoryId, Height, Width, Depth, CollectionId, Price) VALUES('Мебель  30', 7, 1, 743, 395, 638, 10, 685)

--DetailsInFurnitures TABLE
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(41, 18, 0, 1, 10)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(25, 20, 0, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(19, 10, 1, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(23, 16, 1, 1, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(56, 5, 1, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(58, 5, 2, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(45, 17, 2, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(13, 3, 2, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(57, 13, 2, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(5, 3, 2, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(33, 9, 3, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(39, 14, 3, 1, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(38, 3, 3, 1, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(44, 15, 3, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(47, 6, 4, 1, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(35, 1, 4, 1, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(43, 4, 4, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(27, 1, 4, 1, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(22, 2, 5, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(23, 10, 5, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(13, 8, 5, 1, 10)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(5, 9, 5, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(56, 6, 5, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(36, 2, 5, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(26, 16, 6, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(4, 6, 6, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(12, 13, 6, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(39, 3, 6, 1, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(43, 19, 6, 1, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(23, 10, 7, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(42, 18, 7, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(56, 7, 8, 1, 10)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(45, 9, 8, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(32, 7, 8, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(4, 12, 9, 1, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(59, 20, 9, 1, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(49, 6, 9, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(34, 16, 9, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(51, 16, 10, 1, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(33, 7, 10, 1, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(20, 10, 10, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(52, 5, 11, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(24, 3, 11, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(24, 8, 11, 1, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(58, 2, 12, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(19, 11, 12, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(25, 16, 13, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(3, 19, 13, 1, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(18, 9, 14, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(45, 15, 14, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(34, 16, 14, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(26, 6, 14, 1, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(40, 3, 14, 1, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(11, 11, 14, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(47, 19, 15, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(44, 11, 15, 1, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(26, 7, 15, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(14, 14, 15, 1, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(43, 19, 16, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(20, 2, 16, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(18, 20, 16, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(44, 10, 16, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(27, 12, 16, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(49, 11, 17, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(58, 13, 17, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(20, 4, 17, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(45, 19, 18, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(3, 6, 18, 1, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(16, 16, 18, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(58, 1, 18, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(56, 11, 18, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(28, 3, 18, 1, 10)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(47, 14, 19, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(40, 19, 19, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(27, 1, 20, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(40, 4, 20, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(1, 6, 20, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(48, 3, 20, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(23, 15, 21, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(57, 10, 21, 1, 10)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(2, 17, 22, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(36, 1, 22, 1, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(8, 2, 22, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(35, 2, 22, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(14, 8, 23, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(46, 3, 23, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(58, 4, 23, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(41, 13, 23, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(5, 6, 23, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(6, 3, 24, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(1, 10, 24, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(14, 4, 24, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(6, 17, 24, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(50, 8, 25, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(44, 4, 25, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(4, 20, 25, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(41, 9, 25, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(31, 6, 25, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(17, 18, 25, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(33, 12, 26, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(35, 18, 26, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(7, 1, 26, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(41, 14, 26, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(9, 4, 27, 0, 4)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(23, 9, 27, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(25, 7, 27, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(38, 5, 27, 0, 6)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(14, 3, 27, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(24, 18, 28, 1, 10)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(4, 15, 28, 0, 5)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(38, 3, 28, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(38, 10, 28, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(49, 2, 29, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(5, 12, 29, 0, 7)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(60, 1, 29, 0, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(36, 1, 29, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(56, 2, 29, 1, 8)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(41, 18, 29, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(49, 3, 30, 0, 9)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(17, 5, 30, 0, 2)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(2, 18, 30, 0, 3)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(58, 2, 30, 0, 1)
INSERT INTO DetailsInFurnitures(DetailId, Count, FurnitureId, IsAdditional, TimeToIntegrate) VALUES(50, 8, 30, 0, 2)

--PaymentSystems TABLE
INSERT INTO PaymentSystems(Name) VALUES('PayPal')
INSERT INTO PaymentSystems(Name) VALUES('Готівка')
INSERT INTO PaymentSystems(Name) VALUES('LiqPay')
INSERT INTO PaymentSystems(Name) VALUES('WebMoney')
INSERT INTO PaymentSystems(Name) VALUES('Visa/Mastercard')

--Customers TABLE
INSERT INTO Customers(Name, PhoneNumber) VALUES('Олександр', '+380158088')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Роман', '+380686043')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Андрій', '+380876149')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Петро', '+380137976')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Сергій', '+380870287')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Михайло', '+380384531')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Ігор', '+380601086')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Олег', '+380226908')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Володимир', '+380309978')
INSERT INTO Customers(Name, PhoneNumber) VALUES('Назар', '+380187699')

--Posts TABLE
INSERT INTO Posts(Name, Salary) VALUES('Менеджер з продажу', 1100)
INSERT INTO Posts(Name, Salary) VALUES('Менеджер з поставок', 1000)
INSERT INTO Posts(Name, Salary) VALUES('Фахівець з виробництва', 700)
INSERT INTO Posts(Name, Salary) VALUES('Працівник складу', 600)
INSERT INTO Posts(Name, Salary) VALUES('Адмін', 2000)

--Workers TABLE
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(3, 'Олександр', 'Брітвін', 'worker0@gmail.com', '+380349123', 'tjrqtwpwdi', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(2, 'Роман', 'Зібайло', 'worker1@gmail.com', '+380420923', 'daapbuhkpe', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(5, 'Андрій', 'Холодний', 'worker2@gmail.com', '+380220460', 'iebdxlweaw', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(2, 'Петро', 'Захватка', 'worker3@gmail.com', '+380138996', 'lhtqsmqoyh', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(5, 'Сергій', 'Бухів', 'worker4@gmail.com', '+380460243', 'djuivqekyc', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(1, 'Михайло', 'Нечай', 'worker5@gmail.com', '+380792891', 'oewdsgrrbr', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(1, 'Ігор', 'Брітвін', 'worker6@gmail.com', '+380210433', 'diqreybyvi', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(1, 'Олег', 'Брітвін', 'worker7@gmail.com', '+380015428', 'xexanafrwc', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(4, 'Володимир', 'Зібайло', 'worker8@gmail.com', '+380650681', 'fvogerefqw', 'Вільний')
INSERT INTO Workers(PostID, Name, Surname, Email, PhoneNumber, Password, Status) VALUES(4, 'Назар', 'Мазурик', 'worker9@gmail.com', '+380529660', 'vojzocclwn', 'Вільний')
